### ISSUE TITLE
Namespace of test cases is incorrect

### ISSUE THREAD

**Issue by robinvdvleuten** [broadway/event-store-mongodb#5]
Currently the namespace of the test cases (`Broadway\\EventStore\\Mongo\\`) are different from the library's namespace (`Broadway\\EventStore\\MongoDB\\`). These should be the the same.

**Comment by othillo** [comment]
would you be so kind to create a PR for this?

**Comment by robinvdvleuten** [comment]
@othillo sure! I'll add it to my todolist 👍

**Comment by othillo** [comment]
fixed in #14
